##Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/loanwatch
spring.datasource.username=root
spring.datasource.password=root123

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# App port
server.port=8080
jwt.secret=loanwatch@myproject@secret@key@2026@secure
spring.security.user.name=admin
spring.security.user.password=admin
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false